"""penambahan_seluruh_tabel_cms

Revision ID: 5aa5f59d898b
Revises: ac467ffc89c6
Create Date: 2026-06-08 11:52:22.844329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa5f59d898b'
down_revision: Union[str, Sequence[str], None] = 'ac467ffc89c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lensa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_gambar', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lensa_id'), 'lensa', ['id'], unique=False)
    op.create_table('pesan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.Column('tanggal_dikirim', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesan_id'), 'pesan', ['id'], unique=False)
    op.create_table('profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bagian', sa.String(), nullable=True),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profil_bagian'), 'profil', ['bagian'], unique=True)
    op.create_index(op.f('ix_profil_id'), 'profil', ['id'], unique=False)
    op.create_table('rekam_jejak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peran', sa.String(), nullable=True),
    sa.Column('institusi', sa.String(), nullable=True),
    sa.Column('periode_mulai', sa.String(), nullable=True),
    sa.Column('periode_selesai', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rekam_jejak_id'), 'rekam_jejak', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rekam_jejak_id'), table_name='rekam_jejak')
    op.drop_table('rekam_jejak')
    op.drop_index(op.f('ix_profil_id'), table_name='profil')
    op.drop_index(op.f('ix_profil_bagian'), table_name='profil')
    op.drop_table('profil')
    op.drop_index(op.f('ix_pesan_id'), table_name='pesan')
    op.drop_table('pesan')
    op.drop_index(op.f('ix_lensa_id'), table_name='lensa')
    op.drop_table('lensa')
    # ### end Alembic commands ###
