"""penambahan_seluruh_tabel_cms

Revision ID: 70ce197491c9
Revises: 5aa5f59d898b
Create Date: 2026-06-08 12:00:51.148317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ce197491c9'
down_revision: Union[str, Sequence[str], None] = '5aa5f59d898b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
