"""inisialisasi_tabel_awal

Revision ID: ac467ffc89c6
Revises: 
Create Date: 2026-06-08 10:53:37.673534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac467ffc89c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('judul', sa.String(), nullable=True),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.Column('tanggal_publikasi', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artikel_id'), 'artikel', ['id'], unique=False)
    op.create_index(op.f('ix_artikel_judul'), 'artikel', ['judul'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_judul'), 'projects', ['judul'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_judul'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_artikel_judul'), table_name='artikel')
    op.drop_index(op.f('ix_artikel_id'), table_name='artikel')
    op.drop_table('artikel')
    # ### end Alembic commands ###
